org.gradle.jvmargs=-Xmx2048M

loom.platform=fabric

## Minecraft
minecraft_version=1.20.1
parchment_version=2023.09.03
yarn_mappings=1.20.1+build.10
loader_version=0.15.11
fabric_version=0.92.1+1.20.1

## Mod
mod_id=etched_refabricated
mod_version=1.1.0
mod_name=Etched Refabricated
mod_description=A new form of entertainment.
archives_base_name=etched-refabricated
maven_group=gg.moonflower

# Dependencies (1.20.1 baseline; overridden per version in versions/<ver>/gradle.properties)
devauth_version=1.1.1
forge_cofig_api_version=8.0.0
registrate_version=1.3.62-MC1.20.1
yacl_version=3.4.4+1.20.1-fabric
modmenu_version=7.1.0
mixinextras_version=0.3.6